server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: pacientes-service
          uri: lb://PACIENTES-SERVICE
          predicates:
            - Path=/api/v1/pacientes/**
        - id: medico-service
          uri: lb://MEDICO-SERVICE
          predicates:
            - Path=/api/medicos/**
        - id: cita-service
          uri: lb://CITA-SERVICE
          predicates:
            - Path=/api/citas/**,/api/v2/citas/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
