# Configuración Base de Datos para Testing
# Permite correr pruebas en una base MySQL limpia y separada
spring.datasource.url=jdbc:mysql://localhost:3308/saludplus_db_test?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Seguridad
spring.security.user.name=admin
spring.security.user.password=seguridad2026
